# Generated by Django 5.0.1 on 2024-01-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='first-blog-title'),
            preserve_default=False,
        ),
    ]
